### ISSUE TITLE
Phase3 Todos

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist-skills/kubernetes-pod-health-skill#6]
- [x] Configuration updates
- [x] Install script changes
- [x] Sign payloads, and send to provided endpoint
- [x] Declare dependency on Kubernetes integration in YAML
- [x] Use Slack channel parameter

## Installation command

`bash -c "ATM_WORKSPACE=AJPEMAAKJ; K8S_CLUSTER=sdfsd; WEBHOOK_URL=https://webhook-staging.atomist.services/atomist/resource/29ebc661-712e-4bba-885f-6d322a7f0fed; WEBHOOK_SECRET=9cdae0cc-2ac1-4d87-9143-949f0695ba0e; $(curl -fsSL https://static.atomist.com/atomist-k8s-integration.bash)"`

## Sign payloads

Put signature in header `x-atomist-signature`.

## Declare dependency

Include this for Kubernetes:

```yaml
resourceProviders:
- name: kubernetes_cluster
  description: Kubernetes cluster to monitor
  typeName: KubernetesClusterProvider
  maxAllowed: 1
  minRequired: 1
```

and for Slack:

```yaml
resourceProviders:
- name: slack
  description: Slack
  typeName: SlackResourceProvider
  minRequired: 1
  maxAllowed: 1
```

## Use Slack channel parameter

In progress!

You can declare a requirement for the parameter:

```yaml
parameters:
  - chatChannels:
      name: output_channels
      displayName: Chat channel
      description: Name of chat channel to send messages to
      minRequired: 1
      maxAllowed: 3
      required: true
```

The skill will get a payload like this:

```yaml
  parameters:
  - name: output_channels
    value:
    - channelName: announce
      channelId: C3P5LDGR4
      chatTeamId: T095SFFBK
      resourceProviderId: slack_com_id
    - channelName: support
      channelId: C2WAM8AJK
      chatTeamId: T095SFFBK
      resourceProviderId: slack_com_id
```
